import { FormField } from "@/types/FormConfig";
export const residentialApartmentFields: FormField[] = [
  {
    id: "propertyName",
    label: "Property/Project Name",
    type: "text",
    required: true,
    placeholder: "Enter property name",
    colspan: 6,
    conditional: false,
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
  },

  {
    id: "apartmentType",
    label: "Apartment Type",
    type: "select",
    required: true,
    placeholder: "Select apartment type",
    options: [
      { label: "Simplex", value: "Simple" },
      { label: "Duplex", value: "Duplex" },
      { label: "Triplex", value: "Triplex" },
      { label: "Penthouse", value: "Penthouse" },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "sbua",
    label: "Super Built-up Area (sqft)",
    type: "number",
    required: true,
    placeholder: "Enter SBUA in square feet",
    validation: {
      min: 100,
      message: "SBUA must be at least 100 sqft",
    },
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "carpetArea",
    label: "Carpet Area (sqft)",
    type: "number",
    required: false,
    placeholder: "Enter carpet area in square feet",
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "doorFacing",
    label: "Door Facing",
    type: "select",
    required: true,
    placeholder: "Select door facing direction",
    options: [
      { label: "North", value: "North" },
      { label: "South", value: "South" },
      { label: "East", value: "East" },
      { label: "West", value: "West" },
    ],
    dependsOn: {
      field: "category",
      values: ["residential"],
    },
    colspan: 6,
    conditional: true,
  },

  {
    id: "floorNo",
    label: "Floor",
    type: "number",
    required: true,
    placeholder: "Enter floor number",
    validation: {
      min: 0,
      message: "Floor number must be 0 or higher",
    },
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "totalFloors",
    label: "Total Floors in Building",
    type: "number",
    required: false,
    placeholder: "Enter total floors",
    validation: {
      min: 1,
      message: "Total floors must be at least 1",
    },
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "furnishing",
    label: "Furnishing",
    type: "select",
    required: true,
    placeholder: "Select furnishing status",
    options: [
      { label: "Unfurnished", value: "Unfurnished" },
      { label: "Semi-Furnished", value: "Semi-Furnished" },
      { label: "Furnished", value: "Furnished" },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "noOfBedrooms",
    label: "Number of Bedrooms",
    type: "select",
    required: true,
    placeholder: "Select number of bedrooms",
    options: [
      { label: "1 BHK", value: 1 },
      { label: "2 BHK", value: 2 },
      { label: "3 BHK", value: 3 },
      { label: "4 BHK", value: 4 },
      { label: "5 BHK", value: 5 },
      { label: "6 BHK", value: 6 },
      { label: "7 BHK", value: 7 },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },

  {
    id: "extraRooms",
    label: "Extra Rooms",
    type: "multiselect",
    required: false,
    placeholder: "Select extra rooms",
    options: [
      { label: "Servant Room", value: "Servant Room" },
      { label: "Study Room", value: "Study Room" },
      { label: "Pooja Room", value: "Pooja Room" },
      { label: "Other", value: "Other" },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "noOfBathrooms",
    label: "Number of Bathrooms",
    type: "select",
    required: true,
    placeholder: "Select number of bathrooms",
    options: [
      { label: "1", value: 1 },
      { label: "2", value: 2 },
      { label: "3", value: 3 },
      { label: "4", value: 4 },
      { label: "5", value: 5 },
      { label: "5+", value: "5+" },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "noOfBalconies",
    label: "Number of Balconies",
    type: "select",
    required: true,
    placeholder: "Select number of balconies",
    options: [
      { label: "0", value: 0 },
      { label: "1", value: 1 },
      { label: "2", value: 2 },
      { label: "3", value: 3 },
      { label: "4", value: 4 },
      { label: "5", value: 5 },
      { label: "5+", value: "5+" },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "balconyFacing",
    label: "Balcony Facing",
    type: "select",
    required: false,
    placeholder: "Select balcony facing",
    options: [
      { label: "Inside", value: "Inside" },
      { label: "Outside", value: "Outside" },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },

  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "Ready to Move" },
      { label: "Under Construction", value: "Under Construction" },
    ],
    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "New" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ Years" },
    ],

    dependsOn: {
      field: "residentialSubCategory",
      values: ["apartment"],
    },
    colspan: 6,
    conditional: true,
  },
];
