export const appartmentComponents = [
  {
    label: "Community Type",
    type: "radioSelect",
    field: "communityType",
    options: [
      { label: "Gated", value: "Gated" },
      { label: "Independent", value: "Independent" },
    ],
    colspan: 2,
  },
  {
    type: "Project Name",
    colspan: 2,
  },
  {
    label: "Apartment Type",
    type: "slider",
    field: "subType",
    options: [
      { label: "Simplex", value: "Simplex" },
      { label: "Duplex", value: "Duplex" },
      { label: "Triplex", value: "Triplex" },
      { label: "Penthouse", value: "Penthouse" },
    ],
    colspan: 2,
  },
  {
    label: "SBUA",
    type: "textInput",
    field: "sbua",
    suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Carpet Area",
    type: "textInput",
    field: "carpet",
    suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Floor No.",
    type: "textInput",
    field: "exactFloor",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
    footer: "Note: Exact Floor wont be mentioned",
  },
  {
    label: "Door Facing",
    type: "Dropdown",
    field: "facing",
    option: [
      { label: "North", value: "North" },
      { label: "East", value: "East" },
      { label: "South", value: "South" },
      { label: "West", value: "West" },
      { label: "North-East", value: "North-East" },
      { label: "North-West", value: "North-West" },
      { label: "South-West", value: "South-West" },
      { label: "South-East", value: "South-East" },
    ],
    colspan: 1,
  },
  {
    label: "Unit No.",
    type: "textInput",
    field: "unitNo",
    placeholder: "C 456",
    // keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Furnishing",
    type: "Dropdown",
    field: "furnishing",
    option: [
      { label: "Full Furnished", value: "fullFurnished" },
      { label: "Semi Furnished", value: "semiFurnished" },
      { label: "Unfurnished", value: "unFurnished" },
    ],
    colspan: 1,
  },
  {
    label: "No of Bedrooms",
    type: "slider",
    field: "unitType",
    footer: 'Note: This excludes study rooms and servant rooms.',
    options: [
      { label: "Studio", value: "studio" },
      { label: "1 BHK", value: "1 BHK" },
      { label: "2 BHK", value: "2 BHK" },
      { label: "3 BHK", value: "3 BHK" },
      { label: "4 BHK", value: "4 BHK" },
      { label: "5 BHK", value: "5 BHK" },
      { label: "6 BHK", value: "6 BHK" },
      { label: "7 BHK", value: "7 BHK" },
      { label: "8 BHK", value: "8 BHK" },
      { label: "9 BHK", value: "9 BHK" },
      { label: "10 BHK", value: "10 BHK" },
    ],
    colspan: 2,
  },
  {
    label: "Extra Room",
    type: "multiSelectSlider",
    field: "extraRoom",
    options: [
      { label: "Servent Room", value: "serventRoom" },
      { label: "Study Room", value: "studyRoom" },
    ],
    colspan: 2,
  },
  {
    label: "No of Bathrooms",
    type: "slider",
    field: "noOfBathrooms",
    options: [
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "7", value: "7" },
      { label: "8", value: "8" },
      { label: "9", value: "9" },
      { label: "10", value: "10" },
    ],
    colspan: 2,
  },
  {
    label: "No of Balconies",
    type: "slider",
    field: "noOfBalconies",
    options: [
      { label: "0", value: "0" },
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "7", value: "7" },
      { label: "8", value: "8" },
      { label: "9", value: "9" },
      { label: "10", value: "10" },
    ],
    colspan: 2,
  },
  {
    label: "Total Ask Price",
    type: "TotalAskPrice",
    field: "totalAskPrice",
    colspan: 2,
  },
  {
    label: "Hand Over Date",
    type: "MonthYearPicker",
    field: "handoverDate",
    colspan: 2,
  },
  {
    label: "Ready to move",
    type: "Checkbox",
    field: "currentStatus",
    colspan: 2,
  },
  {
    label: "Building Age (Yrs)",
    type: "slider",
    field: "buildingAge",
    placeholder: "0000",
    options: [
      { label: "New Building", value: "New Building" },
      { label: "1-5 Yrs", value: "1-5 Yrs" },
      { label: "6-10 Yrs", value: "6-10 Yrs" },
      { label: "11-15 Yrs", value: "11-15 Yrs" },
      { label: "15+ Yrs", value: "15+ Yrs" },
    ],
    colspan: 2,
  },
  {
    label: "Balcony Facing",
    type: "radioSelect",
    field: "balconyFacing",
    options: [
      { label: "Inside", value: "inside" },
      { label: "Outside", value: "outside" },
    ],
    colspan: 2,
  },
  {
    label: "UDS",
    type: "textInput",
    field: "uds",
    suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Car Park",
    type: "textInput",
    field: "carPark",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Corner Unit",
    type: "Checkbox",
    field: "cornerUnit",
    colspan: 1,
  },
  {
    label: "Exclusive",
    type: "Checkbox",
    field: "exclusive",
    colspan: 1,
  },
  {
    label: "Tenanted",
    type: "Checkbox",
    field: "tenanted",
    colspan: 1,
  },
  {
    label: "OC Received",
    type: "Checkbox",
    field: "ocReceived",
    colspan: 1,
  },
  {
    label: "Rental Income (Per Month)",
    type: "textInput",
    field: "rentalIncome",
    placeholder: "7500",
    keyboardType: "numeric",
    colspan: 2,
    prefix: "₹ ",
    numberToStringFooter: true,
  },
  {
    label: "Building Khata",
    type: "Dropdown",
    field: "buildingKhata",
    option: [
      { label: "A-Khata", value: "A-Khata" },
      { label: "B-Khata", value: "B-Khata" },
    ],
    colspan: 1,
  },
  {
    label: "Land Khata",
    type: "Dropdown",
    field: "landKhata",
    option: [
      { label: "A-Khata", value: "A-Khata" },
      { label: "B-Khata", value: "B-Khata" },
    ],
    colspan: 1,
  },
  {
    label: "E-Khata",
    type: "Checkbox",
    field: "eKhata",
    colspan: 2,
  },
  {
    label: "BIAPPA Approved Khata",
    type: "Checkbox",
    field: "biappaApproved",
    colspan: 2,
  },
  {
    label: "BDA Approved Khata",
    type: "Checkbox",
    field: "bdaApproved",
    colspan: 2,
  },
  {
    type: "Document",
    colspan: 2,
  },
  {
    label: "Extra Details",
    type: "ExtraDetails",
    field: "extraDetails",
    colspan: 2,
  },
];
