export const plotComponents = [
  {
    label: "Community Type",
    type: "radioSelect",
    field: "communityType",
    options: [
      { label: "Gated", value: "Gated" },
      { label: "Independent", value: "Independent" },
    ],
    colspan: 2,
  },
  {
    label: "Plot No.",
    type: "textInput",
    field: "unitNo",
    // suffix: "Sqft",
    placeholder: "A - 03",
    // keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Plot Size",
    type: "textInput",
    field: "plotSize",
    // suffix: "Sqft",
    placeholder: "A - 03",
    // keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Odd Sized",
    type: "Checkbox",
    field: "oddSized",
    colspan: 2,
  },
  {
    label: "Plot Length",
    type: "textInput",
    field: "plotLength",
    // suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Plot Breadth",
    type: "textInput",
    field: "plotBreadth",
    // suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Facing",
    type: "Dropdown",
    field: "facing",
    option: [
      { label: "North", value: "North" },
      { label: "North-East", value: "North-East" },
      { label: "East", value: "East" },
      { label: "South-East", value: "South-East" },
      { label: "South", value: "South" },
      { label: "South-West", value: "South-West" },
      { label: "West", value: "West" },
      { label: "North-West", value: "North-West" },
    ],
    colspan: 2,
  },
  //TotalAskPrice
  {
    label: "Total Ask Price",
    type: "TotalAskPrice",
    colspan: 2,
  },
  {
    label: "Hand Over Date",
    type: "MonthYearPicker",
    field: "handoverDate",
    colspan: 2,
  },
  {
    label: "Ready to move",
    type: "Checkbox",
    field: "readyToMove",
    colspan: 2,
  },
  {
    label: "Inside or Outside Facing",
    type: "radioSelect",
    field: "insideOutside",
    options: [
      { label: "Inside", value: "Inside" },
      { label: "Outside", value: "Outside" },
    ],
    colspan: 2,
  },
  {
    label: "Corner Plot",
    type: "Checkbox",
    field: "cornerUnit",
    colspan: 1,
  },
  {
    label: "Exclusive",
    type: "Checkbox",
    field: "exclusive",
    colspan: 1,
  },
  {
    label: "Land Khata",
    type: "Dropdown",
    field: "landKhata",
    option: [],
    colspan: 2,
  },
  {
    label: "E-Khata",
    type: "Checkbox",
    field: "eKhata",
    colspan: 2,
  },
  {
    label: "BIAPPA Approved Khata",
    type: "Checkbox",
    field: "biappaAppropved",
    colspan: 2,
  },
  {
    label: "BDA Approved Khata",
    type: "Checkbox",
    field: "bdaApproved",
    colspan: 2,
  },
  //DocumentUpload
  {
    label: "Extra Details",
    type: "ExtraDetails",
    field: "extraDetails",
    colspan: 2,
  },
];
