export const villaComponents = [
  {
    label: "Community Type",
    type: "radioSelect",
    field: "communityType",
    options: [
      { label: "Gated", value: "Gated" },
      { label: "Independent", value: "Independent" },
    ],
    colspan: 2,
  },
  {
    label: "Villa No.",
    type: "textInput",
    field: "VillaNo",
    // suffix: "Sqft",
    placeholder: "C 456",
    // keyboardType: "numeric",
    colspan: 2,
  },
  {
    label: "SBUA",
    type: "textInput",
    field: "sbua",
    suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Structure",
    type: "textInput",
    field: "structure",
    // suffix: "Sqft",
    placeholder: "0000",
    // keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Plot Size",
    type: "textInput",
    field: "plotSize",
    suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Carpet Area",
    type: "textInput",
    field: "catrpet",
    suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Door Facing",
    type: "Dropdown",
    field: "facing",
    option: [
      { label: "North", value: "North" },
      { label: "North-East", value: "North-East" },
      { label: "East", value: "East" },
      { label: "South-East", value: "South-East" },
      { label: "South", value: "South" },
      { label: "South-West", value: "South-West" },
      { label: "West", value: "West" },
      { label: "North-West", value: "North-West" },
    ],
    colspan: 1,
  },
  {
    label: "Furnishing",
    type: "Dropdown",
    field: "furnishing",
    option: [],
    colspan: 1,
  },
  {
    label: "No of Bedrooms",
    type: "slider",
    field: "noOfBedrooms",
    options: [
      { label: "1 BHK", value: "1 BHK" },
      { label: "2 BHK", value: "2 BHK" },
      { label: "3 BHK", value: "3 BHK" },
      { label: "4 BHK", value: "4 BHK" },
      { label: "5 BHK", value: "5 BHK" },
    ],
    colspan: 2,
  },
  {
    label: "No of Bathrooms",
    type: "slider",
    field: "noOfBathrooms",
    options: [
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "7", value: "7" },
      { label: "8", value: "8" },
      { label: "9", value: "9" },
      { label: "10", value: "10" },
    ],
    colspan: 2,
  },
  {
    label: "No of Balconies",
    type: "slider",
    field: "noOfBalconies",
    options: [
      { label: "1", value: "1" },
      { label: "2", value: "2" },
      { label: "3", value: "3" },
      { label: "4", value: "4" },
      { label: "5", value: "5" },
      { label: "6", value: "6" },
      { label: "7", value: "7" },
      { label: "8", value: "8" },
      { label: "9", value: "9" },
      { label: "10", value: "10" },
    ],
    colspan: 2,
  },
  //Total Ask Price
  {
    label: "Hand Over Date",
    type: "MonthYearPicker",
    field: "handoverDate",
    colspan: 2,
  },
  {
    label: "Inside or Outside Facing",
    type: "radioSelect",
    field: "insideOutside",
    options: [
      { label: "Inside", value: "Inside" },
      { label: "Outside", value: "Outside" },
    ],
    colspan: 2,
  },
  {
    label: "UDS",
    type: "textInput",
    field: "uds",
    suffix: "Sqft",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Car Park",
    type: "textInput",
    field: "capPark",
    placeholder: "0000",
    keyboardType: "numeric",
    colspan: 1,
  },
  {
    label: "Corner Unit",
    type: "Checkbox",
    field: "cornerUnit",
    colspan: 1,
  },
  {
    label: "Exclusive",
    type: "Checkbox",
    field: "exclusive",
    colspan: 1,
  },
  {
    label: "Tenanted",
    type: "Checkbox",
    field: "tenanted",
    colspan: 1,
  },
  {
    label: "OC Received",
    type: "Checkbox",
    field: "ocReceived",
    colspan: 1,
  },
  {
    label: "Rental Income",
    type: "textInput",
    field: "rentalIncome",
    placeholder: "Type here",
    // keyboardType: "numeric",
    colspan: 2,
  },
  {
    label: "Building Khata",
    type: "Dropdown",
    field: "buildingKhata",
    option: [],
    colspan: 1,
  },
  {
    label: "Land Khata",
    type: "Dropdown",
    field: "landKhata",
    option: [],
    colspan: 1,
  },
  {
    label: "E-Khata",
    type: "Checkbox",
    field: "eKhata",
    colspan: 2,
  },
  {
    label: "BIAPPA Approved Khata",
    type: "Checkbox",
    field: "biappaAppropved",
    colspan: 2,
  },
  {
    label: "BDA Approved Khata",
    type: "Checkbox",
    field: "bdaApproved",
    colspan: 2,
  },
  //DocumentUpload
  {
    label: "Extra Details",
    type: "ExtraDetails",
    field: "extraDetails",
    colspan: 2,
  },
];