export const areasData = [
    {
        Area: "Central Bangalore",
        MicroMarkets: [
            "B Venkata Reddy Nagar",
            "Basavanagudi",
            "BTM Layout",
            "Chamrajapet",
            "Chickpet",
            "Fraser Town",
            "Jayamahal",
            "Jogupalya",
            "Kempapura Agrahara",
            "Lakkasandra",
            "Malleswaram",
            "Rajajinagar",
            "Sadashivanagar",
            "Shanthi Nagar",
            "Vasanth Nagar",
            "Vishveshwara Puram",
        ],
    },
    {
        Area: "East Bangalore",
        MicroMarkets: [
            "A. Narayanapura",
            "Aavalahalli",
            "AECS Layout",
            "Agaram",
            "Avalahalli",
            "Balagere",
            "Bellandur",
            "Bhoganahalli",
            "Bidaraguppe",
            "Brookefield",
            "Byalahalli",
            "CV Raman Nagar",
            "Carmelaram",
            "Chikkabellandur",
            "Chikkakannalli",
            "Choodasandra",
            "Dodda Nekkundi",
            "Doddakannelli",
            "Domlur",
            "Dommasandra",
            "Garudachar Palya",
            "Gattahalli",
            "Gopasandra",
            "Gulimangala",
            "Gunjur",
            "HAL Airport",
            "Harlur",
            "Harohalli",
            "Hoskote",
            "HSR Layout",
            "Hoodi",
            "Huskuru",
            "Indiranagar",
            "Indlabele",
            "KR Puram",
            "Kachamaranahalli",
            "Kadubeesanahalli",
            "Kadugodi",
            "Kaikondrahalli",
            "Kannamangala",
            "Kasvanahalli",
            "Kodathi",
            "Koramangala",
            "Kyalasanahalli",
            "Mahadevapura",
            "Marathahalli",
            "Mullur",
            "Muthanallur",
            "Naganathapura",
            "Neriga",
            "Panathur",
            "Rayasandra",
            "Sadaramangala",
            "Sarjapura",
            "Somsundarapalya",
            "Varthur",
            "Whitefield",
        ],
    },
    {
        Area: "North Bangalore",
        MicroMarkets: [
            "Airport City",
            "Alur",
            "Bagaluru",
            "Baiyappanahalli",
            "Banasavadi",
            "Bande Bommasandra",
            "Bidarahalli",
            "Bileshivale",
            "Budigere",
            "Budigere Cross",
            "Byappanahalli",
            "Bylakere",
            "Byrathi",
            "Cheemasandra",
            "Chikkabanavara",
            "Chikkagubbi",
            "Dasanayakanahalli",
            "Devanahalli",
            "Dodda Gubbi",
            "Doddaballapur",
            "Gundur",
            "HBR Layout",
            "Hebbal",
            "Hennur",
            "Hesaraghatta",
            "Horamavu",
            "IISC",
            "Jakkur",
            "Jalahalli",
            "Kada agrahara",
            "Kadugondanahalli",
            "Kalkere",
            "Kannuru",
            "KIADB Park",
            "Kommasandra",
            "Kothanur",
            "Mandur",
            "Maralakunte",
            "Margondanahalli",
            "Mitganahalli",
            "Nagavara",
            "Narayanapura",
            "Nimbekaipura",
            "Radhakrishna Temple Ward",
            "Rajanukunte",
            "Ramamurthy Nagar",
            "RT Nagar",
            "Sahakara Nagar",
            "Thanisandra",
            "Vaderahalli",
            "Vidyaranyapura",
            "Vignana Kendra",
            "Vijinapura",
            "Visthar",
            "Yelahanka",
            "Yelahanka Satellite Town",
            "Yerappanahalli",
        ],
    },
    {
        Area: "South Bangalore",
        MicroMarkets: [
            "Adigondanahalli",
            "Akshayanagar",
            "Anekal",
            "Anjanapura",
            "Attibele",
            "Banashankari",
            "Banashankari 6th Stage",
            "Bangalore South",
            "Bannerghatta",
            "Begur",
            "Bettadasanpura",
            "Bilekhalli",
            "Bommanahalli",
            "Bommasandra",
            "Electronic City",
            "Hemmigepura",
            "Hulimangala",
            "JP Nagar",
            "Jayanagar",
            "Jigani",
            "Kaggalipura",
            "Kengeri",
            "Kudlu",
            "Ragihalli",
            "Rajarajeshwari Nagar",
            "Uttarahalli"
        ],
    },
    {
        Area: "West Bangalore",
        MicroMarkets: [
            "Challaghatta",
            "Gongadipura",
            "Lakshmipura",
            "Nagarabhavi",
            "Nagasandra",
            "Nelamangala",
            "Peenya",
            "Peenya Industrial Area",
            "Sulivara",
            "Yeshwantpur"
        ],
    },
];