import { FormField } from "@/types/FormConfig";

export const residentialPlot: FormField[] = [
  {
    id: "propertyName",
    label: "Project Name",
    type: "placesApi",
    required: true,
    placeholder: "Enter property name",
    colspan: 12,
    conditional: false,
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
  },
  {
    id: "plotArea",
    label: "Plot Size",
    type: "number",
    required: true,
    placeholder: "1500",
    validation: {
      min: 100,
      message: "Plot area must be at least 100 sqft",
    },
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
    suffix: "Sqft",
    keyBoardType: "numeric",
    colspan: 12,
    conditional: true,
  },
  {
    id: "facing",
    label: "Facing",
    type: "dropdown",
    required: true,
    placeholder: "Select facing direction",
    options: [
      { label: "North", value: "north" },
      { label: "East", value: "east" },
      { label: "South", value: "south" },
      { label: "West", value: "west" },
      { label: "North-East", value: "north-east" },
      { label: "North-West", value: "north-west" },
      { label: "South-West", value: "south-west" },
      { label: "South-East", value: "south-east" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "plotNo",
    label: "Plot No.",
    type: "text",
    required: false,
    placeholder: "Enter plot number",
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "plotLength",
    label: "Plot Length",
    type: "number",
    required: false,
    placeholder: "0000",
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
    suffix: "Ft",
    keyBoardType: "numeric",
    colspan: 6,
    conditional: true,
  },
  {
    id: "plotBreadth",
    label: "Plot Breadth",
    type: "number",
    required: false,
    placeholder: "0000",
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
    suffix: "Ft",
    keyBoardType: "numeric",
    colspan: 6,
    conditional: true,
  },
  {
    id: "oddSized",
    label: "Odd Sized Plot",
    type: "boolean",
    required: true,
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "ready to move" },
      { label: "Under Construction", value: "under construction" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["plot"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "handoverDate",
    label: "Available From",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        {
          field: "assetType",
          values: ["plot"],
        },
        {
          field: "possession",
          values: ["under construction"],
        },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
];