import { FormField } from "@/types/FormConfig";

export const residentialIndependentBuildingFields: FormField[] = [
  {
    id: "propertyName",
    label: "Property/Project Name",
    type: "text",
    required: true,
    placeholder: "Enter property name",
    colspan: 6,
    conditional: false,
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
  },
  {
    id: "sbua",
    label: "Super Built-up Area (sqft)",
    type: "number",
    required: true,
    placeholder: "Enter SBUA in square feet",
    validation: {
      min: 100,
      message: "SBUA must be at least 100 sqft",
    },
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "carpetArea",
    label: "Carpet Area (sqft)",
    type: "number",
    required: false,
    placeholder: "Enter carpet area in square feet",
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "plotArea",
    label: "Plot Area (sqft)",
    type: "number",
    required: true,
    placeholder: "Enter plot area in square feet",
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "structure",
    label: "Structure",
    type: "text",
    required: true,
    placeholder: "E.g., G+1, G+2",
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "furnishing",
    label: "Furnishing",
    type: "select",
    required: true,
    placeholder: "Select furnishing status",
    options: [
      { label: "Unfurnished", value: "Unfurnished" },
      { label: "Semi-Furnished", value: "Semi-Furnished" },
      { label: "Furnished", value: "Furnished" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "facing",
    label: "Facing (Main Door)",
    type: "select",
    required: true,
    placeholder: "Select facing direction",
    options: [
      { label: "North", value: "North" },
      { label: "South", value: "South" },
      { label: "East", value: "East" },
      { label: "West", value: "West" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "balconyFacing",
    label: "Balcony Facing",
    type: "select",
    required: false,
    placeholder: "Select balcony facing",
    options: [
      { label: "Inside", value: "Inside" },
      { label: "Outside", value: "Outside" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "totalFloors",
    label: "Number of Floors",
    type: "number",
    required: false,
    placeholder: "Enter total floors in building",
    validation: {
      min: 1,
      message: "Total floors must be at least 1",
    },
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "noOfBedrooms",
    label: "Number of Bedrooms",
    type: "select",
    required: true,
    placeholder: "Select number of bedrooms",
    options: [
      { label: "1 BHK", value: 1 },
      { label: "2 BHK", value: 2 },
      { label: "3 BHK", value: 3 },
      { label: "4 BHK", value: 4 },
      { label: "5 BHK", value: 5 },
      { label: "6 BHK", value: 6 },
      { label: "7 BHK", value: 7 },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "extraRooms",
    label: "Extra Rooms",
    type: "multiselect",
    required: false,
    placeholder: "Select extra rooms",
    options: [
      { label: "Servant Room", value: "Servant Room" },
      { label: "Study Room", value: "Study Room" },
      { label: "Pooja Room", value: "Pooja Room" },
      { label: "Other", value: "Other" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "noOfBathrooms",
    label: "Number of Bathrooms",
    type: "select",
    required: true,
    placeholder: "Select number of bathrooms",
    options: [
      { label: "1", value: 1 },
      { label: "2", value: 2 },
      { label: "3", value: 3 },
      { label: "4", value: 4 },
      { label: "5", value: 5 },
      { label: "5+", value: "5+" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "Ready to Move" },
      { label: "Under Construction", value: "Under Construction" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "New" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ Years" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "uds",
    label: "Undivided Share (sqft)",
    type: "number",
    required: false,
    placeholder: "Enter UDS in square feet",
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "unitNumber",
    label: "Unit Number",
    type: "text",
    required: false,
    placeholder: "Enter unit number",
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "handOverDate",
    label: "Hand Over Date",
    type: "date",
    required: false,
    placeholder: "Select hand over date",
    dependsOn: {
      field: "assetType",
      values: ["independent house"],
    },
    colspan: 6,
    conditional: true,
  },
];
