import { FormField } from "@/types/FormConfig";

export const residentialRowHouseFields: FormField[] = [
  {
    id: "propertyName",
    label: "Project Name",
    type: "text",
    required: true,
    placeholder: "Enter property name",
    colspan: 12,
    conditional: false,
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
  },
  {
    id: "sbua",
    label: "SBUA",
    type: "number",
    required: true,
    placeholder: "Enter SBUA in square feet",
    validation: {
      min: 100,
      message: "SBUA must be at least 100 sqft",
    },
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "plotArea",
    label: "Plot Area",
    type: "number",
    required: true,
    placeholder: "Enter plot area in square feet",
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "structure",
    label: "Structure",
    type: "text",
    required: true,
    placeholder: "E.g., G+1, G+2",
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "furnishing",
    label: "Furnishing",
    type: "select",
    required: true,
    placeholder: "Select furnishing status",
    options: [
      { label: "Unfurnished", value: "Unfurnished" },
      { label: "Semi-Furnished", value: "Semi-Furnished" },
      { label: "Furnished", value: "Furnished" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "noOfBedrooms",
    label: "No. of Bedrooms",
    type: "select",
    required: true,
    placeholder: "Select number of bedrooms",
    options: [
      { label: "1", value: 1 },
      { label: "2", value: 2 },
      { label: "3", value: 3 },
      { label: "4", value: 4 },
      { label: "5", value: 5 },
      { label: "6", value: 6 },
      { label: "7", value: 7 },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "extraRooms",
    label: "Extra Rooms",
    type: "multiselect",
    required: false,
    placeholder: "Select extra rooms",
    options: [
      { label: "Servant Room", value: "Servant Room" },
      { label: "Study Room", value: "Study Room" },
      { label: "Pooja Room", value: "Pooja Room" },
      { label: "Other", value: "Other" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "noOfBathrooms",
    label: "No. of Bathrooms",
    type: "select",
    required: true,
    placeholder: "Select number of bathrooms",
    options: [
      { label: "1", value: 1 },
      { label: "2", value: 2 },
      { label: "3", value: 3 },
      { label: "4", value: 4 },
      { label: "5", value: 5 },
      { label: "5+", value: "5+" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "noOfBalconies",
    label: "No. of Balconies",
    type: "select",
    required: true,
    placeholder: "Select number of balconies",
    options: [
      { label: "0", value: 0 },
      { label: "1", value: 1 },
      { label: "2", value: 2 },
      { label: "3", value: 3 },
      { label: "4", value: 4 },
      { label: "5", value: 5 },
      { label: "5+", value: "5+" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "balconyFacing",
    label: "Balcony Facing",
    type: "select",
    required: false,
    placeholder: "Select balcony facing",
    options: [
      { label: "Inside", value: "Inside" },
      { label: "Outside", value: "Outside" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "Ready to Move" },
      { label: "Under Construction", value: "Under Construction" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "New" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ Years" },
    ],
    dependsOn: {
      field: "assetType",
      values: ["row house"],
    },
    colspan: 12,
    conditional: true,
  },
];
