import { FormField } from "@/types/FormConfig";

export const industrialShedFields: FormField[] = [
  {
    id: "propertyName",
    label: "Project Name",
    type: "text",
    required: true,
    placeholder: "Enter property name",
    colspan: 12,
    conditional: false,
    dependsOn: {
      field: "commercialSubType",
      values: ["Industrial Shed"],
    },
  },
  {
    id: "sbua",
    label: "SBUA",
    type: "number",
    required: true,
    placeholder: "Enter SBUA in square feet",
    validation: {
      min: 100,
      message: "SBUA must be at least 100 sqft",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["Industrial Shed"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "plotArea",
    label: "Plot Area",
    type: "number",
    required: true,
    placeholder: "Enter plot area",
    dependsOn: {
      field: "commercialSubType",
      values: ["Industrial Shed"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "facing",
    label: "Facing",
    type: "dropdown",
    required: true,
    placeholder: "Select facing direction",
    options: [
      { label: "North", value: "North" },
      { label: "South", value: "South" },
      { label: "East", value: "East" },
      { label: "West", value: "West" },
    ],
    dependsOn: {
      field: "commercialSubType",
      values: ["Industrial Shed"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "Ready to Move" },
      { label: "Under Construction", value: "Under Construction" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Industrial Shed"] },
        { field: "listingType", values: ["resale"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "handoverDate",
    label: "Handover Date",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Industrial Shed"] },
        { field: "listingType", values: ["resale"] },
        { field: "possession", values: ["Under Construction"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "readyToMove",
    label: "Ready-To-Move",
    type: "boolean",
    required: true,
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Industrial Shed"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "availableFrom",
    label: "Available From",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Industrial Shed"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "New" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ Years" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Industrial Shed"] },
        { field: "possession", values: ["Ready to Move"] },
        { field: "listingType", values: ["resale"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "New" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ Years" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Industrial Shed"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "suitableFor",
    label: "Suitable For",
    type: "text",
    required: false,
    placeholder: "Enter suitable business types",
    dependsOn: {
      field: "commercialSubType",
      values: ["Industrial Shed"],
    },
    colspan: 12,
    conditional: true,
  },
];
