import { FormField } from "@/types/FormConfig";

export const pgGuestHouseFields: FormField[] = [
  {
    id: "propertyName",
    label: "Project Name",
    type: "placesApi",
    required: true,
    placeholder: "Enter property name",
    colspan: 12,
    conditional: false,
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
  },
  {
    id: "sbua",
    label: "SBUA",
    type: "number",
    required: true,
    placeholder: "1500",
    validation: {
      min: 100,
      message: "SBUA must be at least 100 sqft",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
    suffix: "Sqft",
    keyBoardType: "numeric",
    colspan: 12,
    conditional: true,
  },
  {
    id: "carpetArea",
    label: "Carpet Area",
    type: "number",
    required: false,
    placeholder: "1500",
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
    suffix: "Sqft",
    keyBoardType: "numeric",
    colspan: 12,
    conditional: true,
  },
  {
    id: "plotArea",
    label: "Plot Area",
    type: "number",
    placeholder: "1500",
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
    suffix: "Sqft",
    keyBoardType: "numeric",
    colspan: 6,
    conditional: true,
  },
  {
    id: "facing",
    label: "Facing",
    type: "dropdown",
    required: true,
    placeholder: "Select facing direction",
    options: [
      { label: "North", value: "north" },
      { label: "South", value: "south" },
      { label: "East", value: "east" },
      { label: "West", value: "west" },
    ],
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
    colspan: 23,
    conditional: true,
  },
  {
    id: "structure",
    label: "Structure",
    type: "text",
    required: true,
    placeholder: "E.g., G+1, G+2",
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "totalRooms",
    label: "Total Rooms",
    type: "number",
    required: false,
    placeholder: "0000",
    validation: {
      min: 1,
      message: "Total rooms must be at least 1",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
    keyBoardType: "numeric",
    colspan: 12,
    conditional: true,
  },
  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "ready to move" },
      { label: "Under Construction", value: "under construction" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["pg/guest-house"] },
        { field: "listingType", values: ["resale"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "handOverDate",
    label: "Handover Date",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["pg/guest-house"] },
        { field: "listingType", values: ["resale"] },
        { field: "possession", values: ["under construction"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "new" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ years" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["pg/guest-house"] },
        { field: "listingType", values: ["resale"] },
        { field: "possession", values: ["ready to move"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "readyToMove",
    label: "Ready-To-Move",
    type: "boolean",
    required: true,
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["pg/guest-house"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "handOverDate",
    label: "Available From",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["pg/guest-house"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "waterSupply",
    label: "Water Supply",
    type: "select",
    required: true,
    options: [
      { label: "Yes", value: true },
      { label: "No", value: false },
    ],
    dependsOn: {
      field: "commercialSubType",
      values: ["pg/guest-house"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "typeOfWaterSupply",
    label: "Type of Water Supply",
    type: "select",
    required: true,
    placeholder: "Select water supply type",
    options: [
      { label: "Borewell", value: "borewell" },
      { label: "Cauvery", value: "cauvery" },
    ],
    dependsOn: {
      field: "waterSupply",
      values: [true],
    },
    colspan: 6,
    conditional: true,
  },
];
