import { FormField } from "@/types/FormConfig";

export const warehouseFields: FormField[] = [
  {
    id: "propertyName",
    label: "Project Name",
    type: "placesApi",
    required: true,
    placeholder: "Enter property name",
    colspan: 12,
    conditional: false,
    dependsOn: {
      field: "commercialSubType",
      values: ["warehouse"],
    },
  },
  {
    id: "sbua",
    label: "SBUA",
    type: "number",
    required: true,
    placeholder: "1500",
    validation: {
      min: 100,
      message: "SBUA must be at least 100 sqft",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["warehouse"],
    },
    suffix: "Sqft",
    keyBoardType: "numeric",
    colspan: 12,
    conditional: true,
  },
  {
    id: "plotArea",
    label: "Plot Area",
    type: "number",
    placeholder: "1500",
    dependsOn: {
      field: "commercialSubType",
      values: ["warehouse"],
    },
    suffix: "Sqft",
    keyBoardType: "numeric",
    colspan: 12,
    conditional: true,
  },
  {
    id: "facing",
    label: "Facing",
    type: "dropdown",
    required: true,
    placeholder: "Select facing direction",
    options: [
      { label: "North", value: "north" },
      { label: "East", value: "east" },
      { label: "South", value: "south" },
      { label: "West", value: "west" },
      { label: "North-East", value: "north-east" },
      { label: "North-West", value: "north-west" },
      { label: "South-West", value: "south-west" },
      { label: "South-East", value: "south-east" },
    ],
    dependsOn: {
      field: "commercialSubType",
      values: ["warehouse"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "ready to move" },
      { label: "Under Construction", value: "under construction" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["warehouse"] },
        { field: "listingType", values: ["resale"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "handOverDate",
    label: "Handover Date",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["warehouse"] },
        { field: "listingType", values: ["resale"] },
        { field: "possession", values: ["under construction"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "readyToMove",
    label: "Ready-To-Move",
    type: "boolean",
    required: true,
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["warehouse"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "handOverDate",
    label: "Available From",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["warehouse"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "new" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ years" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["warehouse"] },
        { field: "possession", values: ["ready to move"] },
        { field: "listingType", values: ["resale"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "new" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ years" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["warehouse"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "suitableFor",
    label: "Suitable For",
    type: "multiselect",
    options: [
      { label: "Office", value: "Office" },
      { label: "Coworking", value: "Coworking" },
      { label: "Training", value: "Training" },
      { label: "Callcenter", value: "Callcenter" },
      { label: "Consulting", value: "Consulting" },
      { label: "IT", value: "IT" },
      { label: "BPO", value: "BPO" },
      { label: "Startup", value: "Startup" },
      { label: "Clinic", value: "Clinic" },
      { label: "Diagnostic", value: "Diagnostic" },
      { label: "Wellness", value: "Wellness" },
      { label: "Hospital", value: "Hospital" },
      { label: "Bank", value: "Bank" },
      { label: "Insurance", value: "Insurance" },
      { label: "Finance", value: "Finance" },
      { label: "Brokerage", value: "Brokerage" },
      { label: "Travel", value: "Travel" },
      { label: "Showroom", value: "Showroom" },
      { label: "Banquet", value: "Banquet" },
      { label: "Conference", value: "Conference" },
      { label: "Warehouse", value: "Warehouse" },
      { label: "Logistics", value: "Logistics" },
      { label: "Studio", value: "Studio" },
      { label: "Production", value: "Production" },
      { label: "R&D", value: "R&D" },
      { label: "Corporate", value: "Corporate" },
    ],
    required: false,
    placeholder: "Enter suitable business types",
    dependsOn: {
      field: "commercialSubType",
      values: ["warehouse"],
    },
    colspan: 12,
    conditional: true,
  },
];
