import { FormField } from "@/types/FormConfig";

export const showroomFields: FormField[] = [
  {
    id: "propertyName",
    label: "Project Name",
    type: "text",
    required: true,
    placeholder: "Enter property name",
    colspan: 12,
    conditional: false,
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
  },
  {
    id: "sbua",
    label: "SBUA",
    type: "number",
    required: true,
    placeholder: "Enter SBUA in square feet",
    validation: {
      min: 100,
      message: "SBUA must be at least 100 sqft",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "carpetArea",
    label: "Carpet Area",
    type: "number",
    required: false,
    placeholder: "Enter carpet area in square feet",
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "noOfSeats",
    label: "No. of Seats",
    type: "number",
    required: true,
    placeholder: "Enter seating capacity",
    validation: {
      min: 1,
      message: "Seating capacity must be at least 1",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "facing",
    label: "Facing",
    type: "select",
    required: true,
    placeholder: "Select facing direction",
    options: [
      { label: "North", value: "North" },
      { label: "South", value: "South" },
      { label: "East", value: "East" },
      { label: "West", value: "West" },
    ],
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "floorNumber",
    label: "Floor No.",
    type: "number",
    required: true,
    placeholder: "Enter floor number",
    validation: {
      min: 0,
      message: "Floor number must be 0 or higher",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "totalFloors",
    label: "Total Floors",
    type: "number",
    required: false,
    placeholder: "Enter total floors",
    validation: {
      min: 1,
      message: "Total floors must be at least 1",
    },
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 6,
    conditional: true,
  },
  {
    id: "furnishing",
    label: "Furnishing",
    type: "select",
    required: true,
    placeholder: "Select furnishing status",
    options: [
      { label: "Bare Shell", value: "Bare Shell" },
      { label: "Warm Shell", value: "Warm Shell" },
      { label: "Plug & Play", value: "Plug & Play" },
    ],
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "possession",
    label: "Possession",
    type: "select",
    required: true,
    placeholder: "Select possession status",
    options: [
      { label: "Ready to Move", value: "Ready to Move" },
      { label: "Under Construction", value: "Under Construction" },
    ],
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Showroom"] },
        { field: "listingType", values: ["resale"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "handoverDate",
    label: "Handover Date",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Showroom"] },
        { field: "listingType", values: ["resale"] },
        { field: "possession", values: ["Under Construction"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "readyToMove",
    label: "Ready-To-Move",
    type: "boolean",
    required: true,
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Showroom"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "availableFrom",
    label: "Available From",
    type: "date",
    required: true,
    placeholder: "MM/YYYY",
    dependsOn: {
      conditions: [
        { field: "commercialSubType", values: ["Showroom"] },
        { field: "listingType", values: ["rental"] },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "New" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ Years" },
    ],
    dependsOn: {
      conditions: [
        {
          field: "commercialSubType",
          values: ["Showroom"],
        },
        {
          field: "possession",
          values: ["Ready to Move"],
        },
        {
          field: "listingType",
          values: ["resale"],
        },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "ageOfTheBuilding",
    label: "Age of Building",
    type: "select",
    required: true,
    placeholder: "Select building age",
    options: [
      { label: "New", value: "New" },
      { label: "1-5 years", value: "1-5 years" },
      { label: "6-10 years", value: "6-10 years" },
      { label: "11-15 years", value: "11-15 years" },
      { label: "15+ Years", value: "15+ Years" },
    ],
    dependsOn: {
      conditions: [
        {
          field: "commercialSubType",
          values: ["Showroom"],
        },
        {
          field: "listingType",
          values: ["rental"],
        },
      ],
      logicOperator: "AND",
    },
    colspan: 12,
    conditional: true,
  },
  {
    id: "suitableFor",
    label: "Suitable For",
    type: "text",
    required: false,
    placeholder: "Enter suitable business types",
    dependsOn: {
      field: "commercialSubType",
      values: ["Showroom"],
    },
    colspan: 12,
    conditional: true,
  },
];
